#pragma once

typedef enum
{
    KEYDOWN = 0,
    KEYUP = 1,
    MOUSEBUTTONDOWN = 2,
    MOUSEBUTTONUP = 3,
    MOUSEMOTION = 4,
    MOUSEWHEEL = 5,
    UPDATE = 6,
    KEYDOWNONCE = 7,
    OBJECTPOSITIONCHANGED = 8,
    OBJECTROTATIONCHANGED = 10,
    OBJECTSCALECHANGED = 11
} EventType;